### PR TITLE
Port to 1.19.2 - Forge 43.3.0

### PR DESCRIPTION
**Pull request by F0x06**
Hi, first thanks for this great mod, i ported the mod to `1.19.2` version, hope this helps.

Regards,
F0x06

PS: Attached a zipped .jar for people to test/use
[jeiintegration_1.19.2-9.0.0.zip](https://github.com/SnowShock35/jei-integration/files/13194046/jeiintegration_1.19.2-9.0.0.zip)

### CODE REVIEW

**Comment by hallool** [comment]
Hi is there gona be a 1.20.1 Port?😅

**Comment by F0x06** [comment]
> Hi is there gona be a 1.20.1 Port?😅

Now I'm playing on 1.19, but should be easy to port (if it's like 1.19)

**Comment by hallool** [comment]
> > Hi is there gona be a 1.20.1 Port?😅
> 
> Now I'm playing on 1.19, but should be easy to port (if it's like 1.19)

I actually hqve no Clue how it works and if it is the same

**Comment by F0x06** [comment]
> > > Hi is there gona be a 1.20.1 Port?😅
> > 
> > 
> > Now I'm playing on 1.19, but should be easy to port (if it's like 1.19)
> 
> I actually hqve no Clue how it works and if it is the same

Done ;) https://github.com/SnowShock35/jei-integration/pull/40

**Review by SnowShock35 — APPROVED** [review]

**Comment by F0x06** [comment]
Hi @SnowShock35, when did you plan to release it on CurseForge :) ? 

Thanks

**Comment by SnowShock35** [comment]
> Hi @SnowShock35, when did you plan to release it on CurseForge :) ?
> 
> Thanks

Before 2024. If you need to use it before that simply clone the mod and build it locally. 😃

**Comment by Nikki-Devil** [comment]
> Before 2024. If you need to use it before that simply clone the mod and build it locally. 😃

Hi @SnowShock35 
May I ask if the 1.19.2 version will be soon on Curseforge ? I saw two 1.20 in beta there and saw your message here
Also, thanks @F0x06 for the two ports

**Pull request merged**
